[project]
name = "hybrid"
version = "0.1.0"
description = "A hybrid solution of artificial coding and vibe coding"
requires-python = ">=3.14"
dependencies = [
    "manim>=0.20.1",
    "pywebview[gtk]>=6.2.1",
    "plotly>=5.0.0",
    "nuitka[onefile]>=4.0.8",
]

[project.scripts]
hy-cli = "calc:main"
hy-gui = "calc_gui:main"
hy-build = "build:main"
hy-render = "demo:main"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"
