[project]
name = "pylatum"
version = "0.1.0"
description = "A learning project for calculating the number of theoretical plates in distillation columns"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
hy-cli = "hylatum.src.calc:main"
hy-gui = "hylatum.src.calc_gui:main"
hy-build = "hylatum.src.build:main"
hy-render = "hylatum.src.demo:main"

[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.uv.workspace]
members = [
    "vilatum",
    "hylatum",
]
