[project]
name = "hylatum"
version = "0.1.0"
description = "A hybrid solution of artificial coding and vibe coding"
requires-python = ">=3.14"
dependencies = [
    "pywebview[gtk]>=6.2.1",
    "plotly>=5.0.0",
]

[dependency-groups]
dev = [
    "manim>=0.20.1",
    "matplotlib>=3.10.9",
]
build = [
    "nuitka[onefile]>=4.0.8",
]
